### ISSUE TITLE
modernizer erroneously recommends javax.inject.Inject over com.google.inject.Inject

### ISSUE THREAD

**Issue by hgschmie** [andrewgaul/modernizer-maven-plugin#41] opened 2015-11-16 01:07 UTC
These two are not equivalent, as the google variant supports optional injection. See https://github.com/google/guice/blob/master/core/src/com/google/inject/Inject.java

So https://github.com/andrewgaul/modernizer-maven-plugin/blob/master/src/main/resources/modernizer.xml#L609-L613 is not correct.

**Comment by Stephan202** [comment] 2015-11-16 04:35
Duplicate of #37, fixed in #39. Not yet released, though. :)

**Comment by andrewgaul** [comment] 2015-11-16 06:32
This seems a bit different, #37 removes an erroneous violation for @AutoWired while this tracks @Inject.

**Comment by Stephan202** [comment] 2015-11-16 06:54
@andrewgaul: You're correct. Should not have commented before my first coffee ;).

**Comment by andrewgaul** [comment] 2015-11-17 23:05
Does this also apply to `javax.inject.Provider`?

@ankon What do you think about this issue?

**Comment by ankon** [comment] 2015-11-24 09:58
Good point. Assuming there is no way to catch only those cases where it is equivalent, this suggestion should probably be removed from the default set.

With that said: 
1. What about having two default rule sets, one for "strict-but-possibly-overzealous" and one for "should always be ok"?
2. Instead of using Guice's `optional` attribute, one can use an `OptionalBinder`: see the documentation here http://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/multibindings/OptionalBinder.html, and a quick use description here: https://groups.google.com/d/msg/google-guice/zvhQiZozcDU/1ND3kQ26vY0J

**Closed** 2017-01-17 23:04 UTC
